
version: "3"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 yachtManagment.wsgi:application
    expose:
      - "8080:8000"
    depends_on:
      - db
    # Add any other necessary configuration
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yachtStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
